version: 1.0.{build}
clone_folder: C:\projects\kevinphelps\nuget-packager
clone_script:
- git clone -q --depth=1 https://github.com/vintage-software/vstack.git C:\projects\vintage-software\vstack
- git clone -q --depth=1 https://github.com/vintage-software/vstack-extensions.git C:\projects\vintage-software\vstack-extensions
- git clone -q --depth=1 https://github.com/kevinphelps/git-compare.git C:\projects\kevinphelps\git-compare
- git clone -q --depth=50 --branch=%APPVEYOR_REPO_BRANCH% https://github.com/kevinphelps/nuget-packager.git C:\projects\kevinphelps\nuget-packager
before_build:
- git reset --hard %APPVEYOR_REPO_COMMIT%
- nuget restore C:\projects\vintage-software\vstack-extensions\Vstack.Extensions.sln
- nuget restore C:\projects\kevinphelps\git-compare\GitCompare.sln
- nuget restore C:\projects\kevinphelps\nuget-packager\NugetPackager.sln
build:
  verbosity: minimal
configuration: Release